// @ts-nocheck is forbidden — these types are the contract.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	appInfo: () => typedError<AppInfo, AppError>(__TAURI_INVOKE("app_info")),
};

/* Types */
export type AppError = { kind: "VaultLocked" } | { kind: "WrongPassword"; detail: {
	attemptsRemaining: number,
} } | { kind: "VaultCorrupted"; detail: {
	path: string,
} } | { kind: "VaultNotFound" } | { kind: "VaultAlreadyExists"; detail: {
	path: string,
} } | { kind: "ProjectNotFound"; detail: {
	path: string,
} } | { kind: "SecretNameTaken"; detail: {
	name: string,
} } | { kind: "IoError"; detail: {
	message: string,
} } | { kind: "NoDataDir" };

export type AppInfo = {
	version: string,
	vaultPath: string,
	vaultExists: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

