// @ts-nocheck is forbidden — these types are the contract.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	vaultStatus: () => typedError<VaultStatus, AppError>(__TAURI_INVOKE("vault_status")),
	createVault: (password: string, generateRecoveryKey: boolean) => typedError<CreatedVaultInfo, AppError>(__TAURI_INVOKE("create_vault", { password, generateRecoveryKey })),
	unlock: (passphrase: string) => typedError<UnlockOutcome, AppError>(__TAURI_INVOKE("unlock", { passphrase })),
	lockVault: () => typedError<boolean, AppError>(__TAURI_INVOKE("lock_vault")),
	/**
	 *  Set a new master password from a recovery-key session (no old password
	 *  needed) — or from a normal session as a plain reset.
	 */
	rekey: (newPassword: string) => typedError<null, AppError>(__TAURI_INVOKE("rekey", { newPassword })),
	/**
	 *  Called (throttled) by the frontend on user interaction so real activity
	 *  defers the auto-lock. Every other command already counts via `set_session`
	 *  or its own state access.
	 */
	touchActivity: () => __TAURI_INVOKE<void>("touch_activity"),
};

/** Events */
export const events = {
	vaultLockedEvent: makeEvent<VaultLockedEvent>("vault-locked-event"),
};

/* Types */
export type AppError = { kind: "VaultLocked" } | { kind: "WrongPassword"; detail: {
	/**
	 *  Attempts left before the 5-minute lockout. `null` when the failure
	 *  came from a non-throttled path (e.g. wrong current password during
	 *  a password change).
	 */
	attemptsRemaining: number | null,
} } | { kind: "RateLimited"; detail: {
	retryAfterSeconds: number,
} } | { kind: "VaultCorrupted"; detail: {
	path: string,
} } | { kind: "VaultNotFound" } | { kind: "VaultAlreadyExists"; detail: {
	path: string,
} } | { kind: "ProjectNotFound"; detail: {
	path: string,
} } | { kind: "SecretNameTaken"; detail: {
	name: string,
} } | { kind: "IoError"; detail: {
	message: string,
} } | { kind: "NoDataDir" };

export type CreatedVaultInfo = {
	/**
	 *  Present only when the user opted in. Shown exactly once, never
	 *  persisted anywhere by the frontend.
	 */
	recoveryKey: string | null,
};

export type UnlockOutcome = {
	/**
	 *  True when the recovery key (not the master password) opened the
	 *  vault; the UI then requires setting a new master password.
	 */
	viaRecovery: boolean,
};

/**
 *  Emitted whenever the vault locks for a reason the frontend did not itself
 *  initiate (auto-lock on idle). The UI must drop all vault state and return
 *  to the lock screen.
 */
export type VaultLockedEvent = {
	/**
	 *  "idle" today; "sleep" and "screen-lock" arrive with the platform
	 *  hooks.
	 */
	reason: string,
};

export type VaultStatus = {
	appVersion: string,
	vaultExists: boolean,
	unlocked: boolean,
	viaRecovery: boolean,
	vaultPath: string,
	autoLockMinutes: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

