// @ts-nocheck is forbidden — these types are the contract.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	vaultStatus: () => typedError<VaultStatus, AppError>(__TAURI_INVOKE("vault_status")),
	createVault: (password: string, generateRecoveryKey: boolean) => typedError<CreatedVaultInfo, AppError>(__TAURI_INVOKE("create_vault", { password, generateRecoveryKey })),
	unlock: (passphrase: string) => typedError<UnlockOutcome, AppError>(__TAURI_INVOKE("unlock", { passphrase })),
	lockVault: () => typedError<boolean, AppError>(__TAURI_INVOKE("lock_vault")),
	/**
	 *  Set a new master password from a recovery-key session (no old password
	 *  needed) — or from a normal session as a plain reset.
	 */
	rekey: (newPassword: string) => typedError<null, AppError>(__TAURI_INVOKE("rekey", { newPassword })),
	/**
	 *  Called (throttled) by the frontend on user interaction so real activity
	 *  defers the auto-lock. Every other command already counts via `set_session`
	 *  or its own state access.
	 */
	touchActivity: () => __TAURI_INVOKE<void>("touch_activity"),
	listProjects: () => typedError<ProjectSummary[], AppError>(__TAURI_INVOKE("list_projects")),
	addProject: (name: string, path: string) => typedError<ProjectSummary, AppError>(__TAURI_INVOKE("add_project", { name, path })),
	renameProject: (projectId: string, name: string) => typedError<null, AppError>(__TAURI_INVOKE("rename_project", { projectId, name })),
	removeProject: (projectId: string) => typedError<null, AppError>(__TAURI_INVOKE("remove_project", { projectId })),
	addEnvironment: (projectId: string, name: string, isProduction: boolean) => typedError<null, AppError>(__TAURI_INVOKE("add_environment", { projectId, name, isProduction })),
	removeEnvironment: (projectId: string, envId: string) => typedError<null, AppError>(__TAURI_INVOKE("remove_environment", { projectId, envId })),
	listSecrets: (projectId: string, envId: string) => typedError<SecretMeta[], AppError>(__TAURI_INVOKE("list_secrets", { projectId, envId })),
	addSecret: (projectId: string, envId: string, key: string, value: string, note: string | null) => typedError<null, AppError>(__TAURI_INVOKE("add_secret", { projectId, envId, key, value, note })),
	/**  `value: None` keeps the current value; `note: Some("")` clears the note. */
	updateSecret: (projectId: string, envId: string, secretId: string, key: string | null, value: string | null, note: string | null) => typedError<null, AppError>(__TAURI_INVOKE("update_secret", { projectId, envId, secretId, key, value, note })),
	removeSecret: (projectId: string, envId: string, secretId: string) => typedError<null, AppError>(__TAURI_INVOKE("remove_secret", { projectId, envId, secretId })),
	/**
	 *  The one deliberate path where plaintext crosses to the UI, for display in
	 *  a masked-by-default row the user explicitly revealed. The frontend keeps
	 *  it in component-local state only and drops it on hide/navigation/lock.
	 */
	revealSecret: (projectId: string, envId: string, secretId: string) => typedError<string, AppError>(__TAURI_INVOKE("reveal_secret", { projectId, envId, secretId })),
	/**
	 *  Copy without the plaintext ever entering JS. Returns the auto-clear delay
	 *  so the UI can show an honest countdown.
	 */
	copySecret: (projectId: string, envId: string, secretId: string) => typedError<number, AppError>(__TAURI_INVOKE("copy_secret", { projectId, envId, secretId })),
	/**
	 *  Root-level plaintext env files in the project folder (templates like
	 *  `.env.example` excluded).
	 */
	scanEnvFiles: (projectId: string) => typedError<EnvFileCandidate[], AppError>(__TAURI_INVOKE("scan_env_files", { projectId })),
	/**
	 *  Parse the file and check git history WITHOUT changing anything — the
	 *  user sees exactly what will happen before confirming.
	 */
	previewEnvImport: (projectId: string, envId: string, path: string) => typedError<ImportPreview, AppError>(__TAURI_INVOKE("preview_env_import", { projectId, envId, path })),
	/**
	 *  The ten-second rescue: import into the vault, write `.env.example`, fix
	 *  `.gitignore`, shred the original (7-day backup), report exposure with
	 *  concrete rotation instructions.
	 */
	importEnv: (projectId: string, envId: string, path: string) => typedError<ImportResult, AppError>(__TAURI_INVOKE("import_env", { projectId, envId, path })),
	guardStatus: () => typedError<GuardStatus, AppError>(__TAURI_INVOKE("guard_status")),
	/**  Flip the global Guard switch and re-sync watchers immediately. */
	setGuardEnabled: (enabled: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_guard_enabled", { enabled })),
	/**  Flip a single project's Guard switch and re-sync. */
	setProjectGuardEnabled: (projectId: string, enabled: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_project_guard_enabled", { projectId, enabled })),
	/**
	 *  Analyze every secret in the (unlocked) vault. No secret values ever cross
	 *  the boundary — only names and finding metadata.
	 */
	healthReport: () => typedError<HealthReport, AppError>(__TAURI_INVOKE("health_report")),
	/**
	 *  This vault's share key — its X25519 public key. Teammates encrypt bundles
	 *  to it; safe to display and copy anywhere.
	 */
	shareKey: () => typedError<string, AppError>(__TAURI_INVOKE("share_key")),
	/**
	 *  Export one environment as an encrypted share bundle. Exactly one of
	 *  `passphrase` / `recipient_keys` must be provided (age forbids mixing).
	 */
	exportShareBundle: (projectId: string, envId: string, passphrase: string | null, recipientKeys: string[], expiresInHours: number | null, destPath: string) => typedError<null, AppError>(__TAURI_INVOKE("export_share_bundle", { projectId, envId, passphrase, recipientKeys, expiresInHours, destPath })),
	/**
	 *  What kind of credential opens this bundle file — read from the age header
	 *  without decrypting anything.
	 */
	inspectShareBundle: (path: string) => typedError<ShareBundleKind, AppError>(__TAURI_INVOKE("inspect_share_bundle", { path })),
	/**
	 *  Decrypt a bundle and hold it in Rust as the pending import. Only metadata
	 *  crosses to the UI (DTO rule §4.3) — the values stay here until confirm.
	 *  `passphrase` opens passphrase bundles; `master_password` unwraps the vault
	 *  identity for key bundles (rate-limited like any password attempt).
	 */
	previewShareImport: (path: string, passphrase: string | null, masterPassword: string | null) => typedError<SharePreview, AppError>(__TAURI_INVOKE("preview_share_import", { path, passphrase, masterPassword })),
	/**
	 *  Apply the pending bundle to the chosen project — into an existing
	 *  environment (`env_id`) or a new one (`new_env_name`). The pending bundle
	 *  is kept on failure so the user can retry without re-entering credentials.
	 */
	confirmShareImport: (projectId: string, envId: string | null, newEnvName: string | null) => typedError<ShareImportResult, AppError>(__TAURI_INVOKE("confirm_share_import", { projectId, envId, newEnvName })),
	/**  Drop the pending bundle (zeroizing its values) without importing. */
	cancelShareImport: () => __TAURI_INVOKE<void>("cancel_share_import"),
	/**
	 *  Write a copy of the encrypted vault file to `dest_path`. It is already
	 *  ciphertext — safe for Dropbox, USB sticks, anywhere.
	 */
	exportVaultBackup: (destPath: string) => typedError<null, AppError>(__TAURI_INVOKE("export_vault_backup", { destPath })),
	/**
	 *  Merge another EnvVault file into the open vault. Needs the password of
	 *  the file being imported (it has its own). Deliberately unthrottled: the
	 *  user supplies both the file and its password, so there is nothing of
	 *  theirs to protect with a lockout — and a throttle sidecar would litter
	 *  the folder the file came from.
	 */
	importVaultMerge: (path: string, password: string) => typedError<VaultMergeResult, AppError>(__TAURI_INVOKE("import_vault_merge", { path, password })),
	/**
	 *  Replace the live vault with another EnvVault file. The session is locked
	 *  FIRST so no in-memory state can overwrite the imported file, then the
	 *  swap happens atomically with the previous vault kept in the rolling
	 *  backups. Afterwards the vault opens with the imported file's password.
	 */
	importVaultReplace: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("import_vault_replace", { path })),
};

/** Events */
export const events = {
	guardFindingEvent: makeEvent<GuardFindingEvent>("guard-finding-event"),
	vaultLockedEvent: makeEvent<VaultLockedEvent>("vault-locked-event"),
};

/* Types */
export type AppError = { kind: "VaultLocked" } | { kind: "WrongPassword"; detail: {
	/**
	 *  Attempts left before the 5-minute lockout. `null` when the failure
	 *  came from a non-throttled path (e.g. wrong current password during
	 *  a password change).
	 */
	attemptsRemaining: number | null,
} } | { kind: "RateLimited"; detail: {
	retryAfterSeconds: number,
} } | { kind: "VaultCorrupted"; detail: {
	path: string,
} } | { kind: "VaultNotFound" } | { kind: "VaultAlreadyExists"; detail: {
	path: string,
} } | { kind: "ProjectNotFound"; detail: {
	path: string,
} } | { kind: "SecretNameTaken"; detail: {
	name: string,
} } | { kind: "EnvironmentNameTaken"; detail: {
	name: string,
} } | { kind: "DuplicateProjectPath"; detail: {
	path: string,
} } | { kind: "InvalidInput"; detail: {
	message: string,
} } | { kind: "StaleId" } | { kind: "IoError"; detail: {
	message: string,
} } | { kind: "NoDataDir" } | { kind: "BundleExpired"; detail: {
	/**  RFC 3339 timestamp of when the bundle expired. */
	expiredAt: string,
} } | { kind: "BundleInvalid"; detail: {
	message: string,
} } | { kind: "BundleWrongKey" } | { kind: "InvalidRecipientKey"; detail: {
	message: string,
} };

export type CreatedVaultInfo = {
	/**
	 *  Present only when the user opted in. Shown exactly once, never
	 *  persisted anywhere by the frontend.
	 */
	recoveryKey: string | null,
};

export type EnvFileCandidate = {
	path: string,
	fileName: string,
};

export type EnvironmentSummary = {
	id: string,
	name: string,
	isProduction: boolean,
	secretCount: number,
};

export type ExposureInfo = {
	commitCount: number,
	firstCommit: string | null,
	lastCommit: string | null,
};

/**
 *  Emitted when the Guard catches a dangerous change (spec F6). The UI shows
 *  an in-app banner with a one-click fix in addition to the OS notification.
 */
export type GuardFindingEvent = {
	/**  "env-appeared" | "secret-in-file" | "gitignore-exposed" */
	kind: string,
	projectId: string,
	path: string,
	fileName: string,
	/**  Populated for the "secret-in-file" kind. */
	secretKeys: string[],
};

export type GuardStatus = {
	/**  Global switch. */
	enabled: boolean,
	/**  How many project directories are actively watched right now. */
	watchedCount: number,
};

export type HealthFinding = {
	/**  "stale" | "reused" | "weak" | "exposed" */
	category: string,
	/**  "critical" | "warning" | "info" */
	severity: string,
	title: string,
	fix: string,
	fixUrl: string,
	locations: HealthLocation[],
};

export type HealthLocation = {
	projectId: string,
	projectName: string,
	environmentId: string,
	environmentName: string,
	isProduction: boolean,
	secretId: string,
	secretKey: string,
};

export type HealthReport = {
	findings: HealthFinding[],
	totalSecrets: number,
	criticalCount: number,
	warningCount: number,
};

export type ImportPreview = {
	fileName: string,
	entries: ImportPreviewEntry[],
	warnings: string[],
	exposure: ExposureInfo | null,
};

export type ImportPreviewEntry = {
	key: string,
	valueLength: number,
	detectedLabel: string | null,
	/**
	 *  A secret with this key already exists in the target environment;
	 *  importing will update it (and mark it rotated).
	 */
	willUpdate: boolean,
	/**  This key appeared more than once in the file; the last value wins. */
	hadDuplicates: boolean,
};

export type ImportResult = {
	imported: string[],
	updated: string[],
	examplePath: string | null,
	backupPath: string | null,
	gitignoreUpdated: boolean,
	warnings: string[],
	exposure: ExposureInfo | null,
	rotationAdvice: RotationAdvice[],
};

export type KeyType = "StripeSecret" | "StripePublishable" | "AwsAccessKey" | "AwsSecretKey" | "OpenAi" | "Anthropic" | "GitHubToken" | "GoogleApi" | "SendGrid" | "Twilio" | "DatabaseUrl" | "JwtSecret" | "PrivateKey" | "Generic";

export type ProjectSummary = {
	id: string,
	name: string,
	path: string,
	createdAt: string,
	environments: EnvironmentSummary[],
	guardEnabled: boolean,
};

export type RotationAdvice = {
	keys: string[],
	label: string,
	url: string,
	steps: string,
};

export type SecretMeta = {
	id: string,
	key: string,
	note: string | null,
	detectedType: KeyType | null,
	detectedLabel: string | null,
	createdAt: string,
	rotatedAt: string,
	valueLength: number,
};

export type ShareBundleKind = "passphrase" | "recipientKeys";

export type ShareImportResult = {
	projectName: string,
	environmentName: string,
	createdEnvironment: boolean,
	added: string[],
	updated: string[],
	unchangedCount: number,
};

export type SharePreview = {
	projectName: string,
	environmentName: string,
	isProduction: boolean,
	createdAt: string,
	expiresAt: string | null,
	entries: SharePreviewEntry[],
};

export type SharePreviewEntry = {
	key: string,
	valueLength: number,
	detectedLabel: string | null,
};

export type UnlockOutcome = {
	/**
	 *  True when the recovery key (not the master password) opened the
	 *  vault; the UI then requires setting a new master password.
	 */
	viaRecovery: boolean,
};

/**
 *  Emitted whenever the vault locks for a reason the frontend did not itself
 *  initiate (auto-lock on idle). The UI must drop all vault state and return
 *  to the lock screen.
 */
export type VaultLockedEvent = {
	/**
	 *  "idle" today; "sleep" and "screen-lock" arrive with the platform
	 *  hooks.
	 */
	reason: string,
};

export type VaultMergeResult = {
	projectsAdded: number,
	environmentsAdded: number,
	secretsAdded: number,
	secretsUpdated: number,
};

export type VaultStatus = {
	appVersion: string,
	vaultExists: boolean,
	unlocked: boolean,
	viaRecovery: boolean,
	vaultPath: string,
	autoLockMinutes: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

